### ISSUE TITLE
Boostrap datepicker and select picker not working

### ISSUE THREAD

**Issue by PeterKitonga** [creativetimofficial/paper-dashboard#10]
There seems to be an issue when trying to add a datepicker from https://bootstrap-datepicker.readthedocs.io/en/latest/ and bootstrap select from http://silviomoreto.github.io/bootstrap-select/

Whenever I try to add it like below, the picker is generated but doesnt show

`<input name="campaign_start" id="campaign_start" />`
`<link rel="stylesheet" href="/assets/bootstrap-datepicker/css/bootstrap-datepicker.min.css">`
`<script src="/assets/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>`
`<script>`
`       $(function() {`
`           $('#campaign_start').datepicker();`
`        });`
`</script>`

Any help would be appreciated, thanks

**Comment by alexandru-paduraru** [comment]
@PeterKitonga thank you for using our product. Please go to `assets/css/paper-dashboard.css` on line 1592 where is this class `.dropdown-menu` and replace it with `.dropdown .dropdown-menu` and let us know if that was working fine. If you have further issues please send us a link to your webapp so we can check it and give a solution.

Best,
Alex

**Comment by PeterKitonga** [comment]
@alexandru-paduraru sorry for taking long to reply. I just tried what you suggested and the line with the `.dropdown-menu` is at line 2679. And upon changing it to the suggested class, it still didn't work.
Here is the content of the line currently:
`.dropdown-menu {display: none; }`

**Comment by PeterKitonga** [comment]
I just solved it. I added `.dropdown` class at line 1373

**Comment by rizaldimaulidia** [comment]
I added `.dropdown`, datepicker has been worked now. but when I access my web in mobile, dropdown menu not working. When I delete again `.dropdown`, dropdown menu worked again. Please tell me what the best soulution for this issue, Thank you
