### ISSUE TITLE
Checkboxes malfunction on iPhone

### ISSUE THREAD

**Issue by guarisco** [creativetimofficial/paper-dashboard#13]
On a page with multiple checkboxes, they seem to function as radios where only one can be checked.  Sometimes, they don't check at all.  Sometimes, they work, but not often.

I've confirmed the exact same behaviour on the Creative Tim website as well, so I know it's not my installation or custom changes.

This is on multiple versions of iOS and I'm using Paper Dashboard Pro.

**Comment by dragosct10** [comment]
Hi, @guarisco! To fix the problem please take the uploaded scss partial and go to `assets/sass/paper/_checkbox-radio.scss` and replace with the new one. After that please compile your scss with [Koala](koala-app.com) and be sure that your output path is `assets/css/paper-dashboard.css`.
[_checkbox-radio.scss.zip](https://github.com/creativetimofficial/paper-dashboard/files/1558919/_checkbox-radio.scss.zip)

Regards,
Dragos

**Comment by guarisco** [comment]
Hello Dragos,

I've tried the patched file on two app servers to make sure it's not a one-off, and it's still not working.  They still act like radios, but sometimes allow you to unselect all of the checkboxes.  If it helps, I'll try to capture a video of it happening so you can see it.

If you have a fix in the meantime, please send it along.  Again, it's iPhone with Safari.

Thank you.

**Comment by dragosct10** [comment]
Hi! Yes it will be more efficient to give me a video to see exactly what happened. 

Regards,
Dragos

**Comment by guarisco** [comment]
Here are two videos...one from the iPhone itself, and one old-school recording the actual touches.

https://www.screencast.com/t/jH9nxhLbu

https://www.saloninteractive.com/IMG_1180.MOV

**Comment by dragosct10** [comment]
Hi! I will show you a video of how it will suppose to work for you, after you made the changes that I told you to do and also you can check the link `pd-pro.paperplane.io/examples/forms/extended.html` on your iphone. Maybe you didn't compile your scss after you replaced the scss partial. 

[IMG_4395.MOV.zip](https://github.com/creativetimofficial/paper-dashboard/files/1559921/IMG_4395.MOV.zip)

Regards,
Dragos

**Comment by guarisco** [comment]
Thank you, the patched SCSS file is actually working fine and fixed the problem!  Will this fix make it into the full download soon?  Thanks again.

**Comment by dragosct10** [comment]
Hi, @guarisco! Yes, it will be available in the next update for the product. 

Regards,
Dragos
