### ISSUE TITLE
Nucleo Apps doesnt work in firefox 

### ISSUE THREAD

**Issue by photonauta35** [creativetimofficial/paper-dashboard#17]
I bought Dashboar Paper Pro 2 and when I start any example page in firefox (release 59.0) I have been getting bad request for Nucleo Apps Icon. I was taking look in head calls and I realized that nc is not called that. Could it be a problem? How could I deal with that? 

![selecao_088](https://user-images.githubusercontent.com/641411/41003928-7a45d13c-68ee-11e8-9b34-5d1cb74ab24e.png)

**Comment by groovemen** [comment]
Hello @photonauta35, thank you for using our products, this may be an issue with Firefox.  On local, Firefox doesn't know the correct path to the icons. Try to set your path like `C:\User\Desktop\YourProject...`, not a relative one; or you can run your project on a server. As you can see, the icons from our product(Paper Dashboard) on livePreview is working fine.

<img width="1440" alt="screen shot 2018-06-06 at 10 42 34" src="https://user-images.githubusercontent.com/21063398/41023970-8df5f99a-6976-11e8-980c-b8a9f0573910.png">

Hope these informations helps you.
All the best, 
Stefan

**Comment by groovemen** [comment]
Did you also tried to run your project on npm? here are some steps that you have to follow: https://demos.creative-tim.com/paper-dashboard-2-pro/docs/1.0/components/colors.html

**Comment by photonauta35** [comment]
> Ran into the same issue, use this to properly configure Firefox: https://stackoverflow.com/a/3704578

That's great! Thank you. =)
