### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ghanbari** [creativetimofficial/paper-dashboard#24]
Does theme supports RTL?

**Comment by groovemen** [comment]
Hello @ghanbari, 

Thank you for your interest in working with our products, this theme supports the RTL but you have to implement it. 

Best,
Stefan

**Comment by ghanbari** [comment]
thanks @groovemen 
Is there a simple demo?

**Comment by groovemen** [comment]
Yes, we have RTL example for other products. You can check the following link:  https://demos.creative-tim.com/black-dashboard/examples/rtl.html 

Best, Stefan

**Comment by ghanbari** [comment]
what i must do for rtl version?, 

- change sass files?
- only add rtl direction directive to html?
- or change css files used?

**Comment by groovemen** [comment]
You can have RTL support on your page by simple follow the steps:

You must add on the body tag the class **.rtl-active**
Now you have to add in the head the following tag and remove the tag link with bootstrap by default, like in the example below:

`<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.0.0/css/bootstrap.min.css" integrity="sha384-P4uhUIGk/q1gaD/NdgkBIl3a6QywJjlsFJFk7SPRdruoGddvRVSwv5qFnvZ73cpz" crossorigin="anonymous">`

In the last step you must remove the tag link from javascript at the end of the page with bootstrap by default and replace that link with the following:

`<script src="https://cdn.rtlcss.com/bootstrap/v4.0.0/js/bootstrap.min.js" integrity="sha384-54+cucJ4QbVb99v8dcttx/0JRx4FHMmhOWi4W+xrXpKcsKQodCBwAvu3xxkZAwsH" crossorigin="anonymous"></script>`

**Comment by ghanbari** [comment]
thanks @groovemen

**Comment by ghanbari** [comment]
@groovemen I found a [rtl demo version](http://demo.webcandoo.com/?theme=vue-paper-dashboard)
