### ISSUE TITLE
Navbar components are broken or overlapped when clicked

### ISSUE THREAD

**Issue by alshoja** [creativetimofficial/paper-dashboard#36]
![20191226_011755](https://user-images.githubusercontent.com/22396784/71449929-a0c6cd80-277d-11ea-979b-169ad212be51.jpg)

**Comment by groovemen** [comment]
Hello @alshoja,

Thank you for your interest in working with our products.
It seems that you haven't respected our ISSUE_TEMPLATE, so we are going to close it.
Please add a new comment here, or open a new issue, by filling the mentioned ISSUE_TEMPLATE and please be sure that your issue title is a very small description of your issue as well.

All the best,
Stefan
Developer @ Creative-Tim.com

**Comment by alshoja** [comment]
am sorry for issue template, I haven't seen any issue templates or maybe am not aware of that, can I get what to do for this issue? @groovemen

**Comment by groovemen** [comment]
Please fill the issue_template and provide us more details about your issue. 

Best, 
Stefan
