### ISSUE TITLE
does this project use MIT license?

### ISSUE THREAD

**Issue by haoyuanli** [creativetimofficial/paper-dashboard#37]
The MIT license does not require the footer `credits` to be unchanged, so I'm hoping to get clarification on this. Instead, the requirement is to preserve the original license by `creativeTim` in all or substantial portions of the software, which should certainly be respected.

The reason I asked is, when there's conditions added to the original MIT license, it's now altered and its original force will be in doubt. I'm just looking for a clearer answer.

Thanks!

![image](https://user-images.githubusercontent.com/18109953/72748009-08005380-3b6b-11ea-9079-6673e485c165.png)

**Comment by groovemen** [comment]
Hello @haoyuanli,

Thank you for your interest in working with our products, you can erase the credits from the footer section but you'll need to keep them in the CSS and JS files.

All the best,
 Stefan
