### ISSUE TITLE
[PRO] .input-group-addon incorrect colors when using .has-error and .has-success

### ISSUE THREAD

**Issue by jchernan** [creativetimofficial/paper-dashboard#4]
There's a typo in the `.input-group-addon` definition, where the second `.has-error` should have been `.has-success`:

```
.input-group-addon {
    // ...
    .has-error &{
        color: $danger-color;
        border-color: $danger-color;
    }
    .has-error &{                    // <== TYPO HERE
        color: $success-color;
        border-color: $success-color;
    }
    // ...
}
```

https://github.com/creativetimofficial/paper-dashboard/blob/master/assets/sass/paper/_inputs.scss

**Comment by groovemen** [comment]
Hello @jchernan, this issue is solved in version 2.0.1.
Best, Stefan
