### ISSUE TITLE
PerfectScrollbar not working with sidebar mini on Windows/Chrome + Firefox

### ISSUE THREAD

**Issue by alexandru-paduraru** [creativetimofficial/paper-dashboard#6]
Customer details:

"I'm checking http://demos.creative-tim.com/paper-dashboard-pro/examples/dashboard/overview.html on Windows (Chome & Firefox)

During minifying the sidebar, the UI scroll is defaulting to browser one instead of the one that comes with the theme. Could you please check this and fix?

Thanks"

**Comment by groovemen** [comment]
Solved in the version 2.0.1
